
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import Link from "next/link";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Feskena",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <div className="min-h-screen flex flex-col">
          {/* Site Header with Logo and Title */}
          <header className="w-full flex items-center gap-2 px-6 py-4 bg-white/80 shadow-sm z-30">
            <img src="/star.svg" alt="Logo" width={32} height={32} className="inline-block align-middle mr-2" />
            <span className="text-2xl font-extrabold text-blue-900 tracking-tight">Feskena</span>
          </header>
          <main className="flex-1">
            {children}
          </main>
          <FooterNav />
        </div>
      </body>
    </html>
  );
function FooterNav() {
  return (
    <footer className="w-full bg-white/90 border-t border-blue-100 py-4 px-2 flex flex-col items-center gap-2 text-blue-700 text-sm font-medium shadow-inner z-20">
      <nav className="flex flex-wrap gap-4 md:gap-8 items-center justify-center">
  <Link href="/about" className="hover:underline font-bold">About</Link>
        <Link href="/subscription" className="hover:underline font-bold">One-Time Payment</Link>
        <Link href="/privacy-policy" className="hover:underline font-bold">Privacy Policy</Link>
        <Link href="/terms-of-service" className="hover:underline font-bold">Terms of Service</Link>
  {/* Only one About link should remain. Remove this duplicate if another exists. */}
  <a href="mailto:feskenai@gmail.com" className="hover:underline font-bold">Contact: feskenai@gmail.com</a>
      </nav>
      <div className="text-blue-700 text-xs md:text-sm text-center md:text-right">
        © 2025 Resume &amp; Cover Letter Builder. All rights reserved.
      </div>
    </footer>
  );
}
}
